services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./:/home/node/.n8n
    environment:
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_DEFAULT_LOCALE: pt-BR
      N8N_LOG_LEVEL: info
      N8N_LOG_OUTPUT: file
      N8N_LOG_FILE_LOCATION: /home/node/.n8n/logs/
    restart: unless-stopped
    networks:
      - n8n-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    restart: unless-stopped
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge
